
project_id = "pwiqicyfwvwwgqbxhmvv"

[functions.vapi-webhook]
verify_jwt = false

[functions.process-achievements]
verify_jwt = false

[functions.process-focus-areas]
verify_jwt = false

[functions.process-whatsapp-summaries]
verify_jwt = false

[functions.process-call-summaries]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.scheduled-checkins]
verify_jwt = false

[functions.update-last-demo-call]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.test-scheduled-call]
verify_jwt = false
